### ISSUE TITLE
Default less variables logoTop logoLeft and logoWidth

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#108]
Shouldn't these be empty like the other less.var constants? Now it's not possible to set the less variables in felayout.

```
themes.configuration.less.var.logoTop = 30px
themes.configuration.less.var.logoLeft = 40px
themes.configuration.less.var.logoWidth = 120px
```

**Comment by phathoang** [comment]
Ping @dmh  I guess it's ok to remove the values since they are already set in felayout's customVariables.less?
https://github.com/t3kit/felayout_t3kit/blob/master/dev/styles/customVariables.less

**Comment by dmh** [comment]
I just checked and totally agree with you, I will fix it on theme_t3kit.
That's really weird, as I remember there was a reason why we did like this, but I not remember this reason :)
