### ISSUE TITLE
Uncommented example wrappers

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#109]
In Configuration/FluidStyledContent/FluidContent.pagets
I think these should be commented?

```
TCEFORM.tt_content.wrapper.addItems.100 = Example generic wrapper
TCEFORM.tt_content.layout.addItems.100 = Example generic layout for all content
```

**Comment by dmh** [comment]
The idea was to show an example how to do it, but now I see that this example should be commented by default.
I will fix it as a breaking change, in case that somebody used it in a project.
Thanks!
