### ISSUE TITLE
Adjust TypoScript Conditions

### ISSUE THREAD

**Issue by Artjom-Grigorjew** [t3kit/theme_t3kit#12]
Dear developers,
i´m working with the t3kit and trying to merge it with an other TYPO3 CMS System. 
Now i found these TypoScript Conditions in the dyncss plugin setupts.  The memory of the cache table is increasing, because every site for every condition is stored there.

Could it be possible to adjust the TypoScript conditions in the dyncss plugin setupts?
Best regards
Artjom

**Comment by dmh** [comment]
We added your PR `Adjust TypoScript Conditions`
Thanks for help!
