### ISSUE TITLE
Hidden fields "Link text" and "Link" for editors

### ISSUE THREAD

**Issue by AlexPixelant** [t3kit/theme_t3kit#121]
When user logged in as an editor he/she has not see fields "Link text" and "Link" when creating Content Elements. It can be fixed by marked those fields in Editor usergroup. But maybe its better to fix that in theme_t3kit instead? So you don't have to fix it every time.

**Comment by dmh** [comment]
I can reproduce this problem only with "link text" field in t3kit content elements, but "link" itself shown under editor account. Could you specify content element which has hidden "link" field under editor account?
@AlexPixelant

**Comment by dmh** [comment]
#124

**Comment by AlexPixelant** [comment]
Yes, "Link" is visible under editor because by default it configured so (added as allowed field): https://www.dropbox.com/s/49kr9m33hpf5bsp/Selection_060.png?dl=0

As you see, on screenshot, subheader field ("Link text" in Content Element) doesn't.
@dmh

**Comment by dmh** [comment]
https://github.com/t3kit/t3kit_db/commit/3786587e51112fae236b7b5eebab868e8889308b
