### ISSUE TITLE
Image scaling IE11

### ISSUE THREAD

**Issue by karlfredriklinden** [t3kit/theme_t3kit#140]
Images doesn't respect max-width in IE11

![skarmklipp 2017-03-07 08 39 24](https://cloud.githubusercontent.com/assets/15790154/23646550/970b18ca-0311-11e7-97fc-aaf639dd70ed.png)

Steps to reproduce: 

Create an advanced 2-columns grid, set the size to 9/12 and 3/12. Put a media element in the 3/12 column.

<img width="800" alt="skarmklipp 2017-03-07 08 36 03" src="https://cloud.githubusercontent.com/assets/15790154/23646501/6065dcba-0311-11e7-9f3c-d08af1244e27.png">

**Comment by myroslav321** [comment]
@karlfredriklinden 

Checked on IE11, looks ok

![screenshot_1](https://user-images.githubusercontent.com/20657744/27121023-58c45cd6-50ee-11e7-8452-fce6d751a786.png)
