### ISSUE TITLE
Browser not caching pages

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#145]
Because of this rule in .htaccess the page doesn't get cached by the browser:
`ExpiresByType text/html                             "access plus 0 seconds"`

It's also a problem when using CDN that respects this header.

I suggest setting `config.sendCacheHeaders = 1`. This allows TYPO3 to send the correct cache headers depending on the cache configuration of the specific page.

**Comment by MattiasNilsson** [comment]
Closed after merging #146
