### ISSUE TITLE
News list images not responsive

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#190]
Bigger images causes horizontal scroll because the images are not responsive:
```
plugin.tx_news.settings.list.media.image.maxWidth = 500
plugin.tx_news.settings.list.media.image.maxHeight = 500
```
![t3kithorizontalscroll](https://cloud.githubusercontent.com/assets/14972506/25651538/e6e8b5e2-2fe3-11e7-8919-592eb79f2e28.png)

**Comment by myroslav321** [comment]
@phathoang 
Pull request https://github.com/t3kit/theme_t3kit/pull/242
