### ISSUE TITLE
Issue with gridelements v7.0.5 

### ISSUE THREAD

**Issue by IvayloIvanov** [t3kit/theme_t3kit#191]
Hello,

I have some issues working in the backend:
1. When I create a new content element and I fill the header field, after saving the element the content within the header field disappears
2. When I add a new content element, sometimes, I receive an error message - SQL error: 'Incorrect integer value: '' for column 'tx_gridelements_container' at row 1' 
Working with TYPO3 7.6.15, PHP 7

After Updating the grindelements ext. to the latest version v7.1.0 all the issues are gone.
Unfortunately the theme_t3kit extension has a dependency: 'gridelements' => '7.0.5-7.0.99'.
Is it possible to extend the dependency according the gridelements to the latest version.

Thanks
Ivaylo

**Comment by dmh** [comment]
Hey,
Dependency extended to version 8.0.0.
But keep in mind that Gridelements is not released yet to TYPO3 extension repository, so my suggestion is to use Composer to install extensions.

Thanks
