### ISSUE TITLE
News images, size specification?

### ISSUE THREAD

**Issue by phathoang** [t3kit/theme_t3kit#192]
My smiley gets cropped like this.
![crop](https://cloud.githubusercontent.com/assets/14972506/25666892/2536f2da-3022-11e7-81e0-283035bda1b1.png)
Is there documentation for what size of images that is suited for the different views in news?

**Comment by myroslav321** [comment]
@phathoang 
I didn't find such information in gitbook. 
But image size should be 737 x 510. Also i made a pull request https://github.com/t3kit/theme_t3kit/pull/243
It will fix image cropping for news simple list(in case if uploaded images 737 x 510)

**Comment by dmh** [comment]
@myroslav321 
Please add this info about proper image size for news into Gitbook

Thanks

**Comment by smartestfinance** [comment]
May be a dumb question, but how to start with it? I have a Typo3 installation on my server, I have downloaded your theme kit and now?

Thanks in advance!

**Comment by dmh** [comment]
Fixed:
https://github.com/t3kit/theme_t3kit/pull/243
