### ISSUE TITLE
change config.metaCharset = UTF-8 to metaCharset = utf-8

### ISSUE THREAD

**Issue by MattiasNilsson** [t3kit/theme_t3kit#249]
I only get a white screen in frontend with no html output at all. I imported the db an in backend everything seems good. do you have any idea?
 
Found the problem. regression bug in typo3 8.6.2 metaCharset need to be lowercase LOL. 
please change config.metaCharset = UTF-8 to metaCharset = utf-8

**Comment by huersch** [comment]
actualy the Problem is in EXT:themes, but maybe you can fix it in t3kit anyway
