### ISSUE TITLE
Slider arrow background-image value not working in compression

### ISSUE THREAD

**Issue by aennafae** [t3kit/theme_t3kit#252]
Gooood morning! 
We have a problem with the current background-image value in the slider. When using the compressAndConcatenate = 1 function from TYPO3 the base64 value somehow breaks. Tested it with another base64 image - it worked. How do you handle it in your projects? We can override it for the moment, but i think the image should be fixed. Maybe this link is helpful https://css-tricks.com/probably-dont-base64-svg/. 
![base64iamge](https://user-images.githubusercontent.com/6085021/27902810-5c8174f8-6237-11e7-88a2-c322479361e8.png)
Kind regrads and have a great day,
Anna :)

**Comment by dmh** [comment]
Sorry for the late reply.
I can't reproduce this issue.
TYPO3 BE -> tab Themes -> Expert -> Dev Mode -> enable `Production Mode`

Production Mode:
``` 
config.compressCss = 1
config.compressJs = 1
config.concatenateCss = 1
config.concatenateJs = 1
```

`theme_t3kit/Configuration/TypoScript/Library/config.setupts`

With this option (Production Mode) background-image is still working ok

**Comment by aennafae** [comment]
Thank you. It's fixed with this Commit https://github.com/t3kit/theme_t3kit/pull/269. We use the Bootstrap slider.
