### ISSUE TITLE
Move bootstrap.less in main.less to use Bootstrap variables

### ISSUE THREAD

**Issue by aennafae** [t3kit/theme_t3kit#266]
I would recommend to import the bootstrap.less file in main.less file to use the Bootstrap variables. To override the variables you can add a file named bootstrap-variables.less in styles directory, copy all the bootstrap variables and comment them out.  To override them you can then comment them out. I can make a PR with a recommended implementation.

**Comment by dmh** [comment]
Is it not the same as you did on this PR? https://github.com/t3kit/theme_t3kit/pull/269
I mean add `@import "../../node_modules/bootstrap/less/variables.less"` to `felayout_t3kit/dev/styles/main.less`

**Comment by aennafae** [comment]
Yes, you are right. I just wanted to see if the pull request will be ok for you. We still have to tidy up the less files in order to use the bootstrap variables. :) Should we do that or will you?

**Comment by dmh** [comment]
It is ok for me to have `variables.less`, but I am not sure why we need it, in case that we can't change it. I am not sure what you mean  "tidy up the less files in order to use the bootstrap variables"? Could you explain?

**Comment by aennafae** [comment]
Sure. The advantage to import the boostrap variables in main.less is to use them. You can use all variables form variables.less in your LESS files. Currently you use custom variables and couple of boostrap variables which are overriden in customVariables.less. Now you can use all of them. For example the media queries can now be called via variables.
`@media (min-width: @screen-sm-min) { }` 
You can also copy all bootstrap variables in your customVariables file. But we need them no matter how. ☺️

**Comment by dmh** [comment]
I agree about `variables.less` to use it in Less files, but it ok until we need to change it, and here we have `customVariables.less` to have possibility keep bootstrap updatable but with our rewriting of bootstrap variables.
I would suggest you create PR with those changes, or as least with some examples, and we will continue discussing it there. Is it ok for you?

**Comment by aennafae** [comment]
You also can update bootstrap with the current setup. The variables should only be available in your LESS files for beautiful, maintainable coding :)
I will create a PR soon.
