### ISSUE TITLE
Swiper buttons

### ISSUE THREAD

**Issue by mesosa** [t3kit/theme_t3kit#307]
Change swiper arrows and pagination dots so it is possible to change colors.

**Comment by myroslav321** [comment]
@mesosa I did pull request https://github.com/t3kit/theme_t3kit/pull/331 which fix this issue, but
there is another solution. Right now, arrows are Base64 .svg images on background, and it is possible to change they color by changing 'Base64 code', pls check attached image, so we can just rewrite
![1](https://user-images.githubusercontent.com/20657744/32229291-25c3cf5a-be59-11e7-9555-c5e430dfd53d.png)
 it in subtheme whenever it needs
