### ISSUE TITLE
fix footer styling

### ISSUE THREAD

**Issue by dmh** [t3kit/theme_t3kit#309]
![download](https://user-images.githubusercontent.com/5150636/31384066-0a2329d8-adc6-11e7-8e55-556e7fa8e19c.png)

1. Logo and text aligning
2. Bottom padding too small

**Comment by dmh** [comment]
@dkd-faerber

**Comment by aennafae** [comment]
I will fix this :)

**Comment by aennafae** [comment]
Done by #310
