### ISSUE TITLE
Composer Bug on Extension dyncss

### ISSUE THREAD

**Issue by edekowalski** [t3kit/theme_t3kit#417]
- Installing kaystrobach/dyncss (dev-master 9d44630)Enter passphrase for key '                     /root/.ssh/id_rsa':
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos

Best Regard's
Ede
![unbenannt](https://user-images.githubusercontent.com/2975173/40964446-6d0954fa-68ab-11e8-94e9-711e9d2cee8f.PNG)

**Comment by edekowalski** [comment]
I am sorry, my mistake. I have to adjust my Personal Access Token.

Best Regard's
Eric

**Comment by edekowalski** [comment]
Or does this solution not working?

**Comment by dmh** [comment]
https://github.com/t3kit/t3kit/commit/4ad38f6f100b26b818281a1c45fada8f1254d0a4
