### ISSUE TITLE
PHP Version limited to 7.0.0 so 7.0.+ isn't even posible

### ISSUE THREAD

**Issue by lisandi** [t3kit/theme_t3kit#43]
Required extension "theme_t3kit":
Your PHP version is higher than allowed. You can use PHP versions 5.5.0 - 7.0.0

The same applies to other of your extensions the same!

**Comment by dmh** [comment]
Hi @lisandi,
As I understand, your suggestion is to use 'php'    => '5.5.0-7.0.99', right?

Thanks for feedback.

**Comment by lisandi** [comment]
Hi Dmytro
yes we run i.e. _PHP 7.0.7_

by the way how do you pronounce your last name (just out of interest)

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

 _ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_about.me/andibecker
http://about.me/andibecker--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

---
