### ISSUE TITLE
Composer Require fails

### ISSUE THREAD

**Issue by Valiron** [t3kit/theme_t3kit#44]
I wanted to use Composer to install the theme 
I added in my Composer this: 

```
  "repositories": [
    { "type": "composer", "url": "https://composer.typo3.org/" },
    { "type": "vcs", "url": "https://github.com/t3kit/theme_t3kit" },
    { "type": "vcs", "url": "https://github.com/t3kit/t3kit_extension_tools" }
  ],
```

after I started, I got this error

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for t3kit/theme-t3kit ^1.7 -> satisfiable by t3kit/theme-t3kit[1.7.0].
>     - t3kit/theme-t3kit 1.7.0 requires typo3-ter/fluid-styled-content \* -> no matching package found.

after I looked into my Typo Directory i found an cms-fluid-styled-content , maybe u can fix that

**Comment by michalcyg** [comment]
I have the same problem trying to install via composer.

**Comment by michalcyg** [comment]
I have solved it by adding 

"typo3-ter/fluid-styled-content": "self.version",

in replace section of my main composer.json file

**Comment by dmh** [comment]
https://github.com/t3kit/t3kit_composer
