### ISSUE TITLE
Typoscript and pagets includes

### ISSUE THREAD

**Issue by pixelmatseriks** [t3kit/theme_t3kit#451]
I suggest to separate and use standard TYPO3 way to include typoscript and pagets ("Include static (from extensions)"). 
This way it will be easier to select what configurations and features to use and also easier to use other configurations.

E.g
Theme_t3kit: base configuration
Theme_t3kit: news configuration
Theme_t3kit: solr configuration
etc.

**Comment by edekowalski** [comment]
This is a very good solution. 
Best regards
Ede
