### ISSUE TITLE
Plans on updating the TER version 

### ISSUE THREAD

**Issue by ferdynator** [t3kit/theme_t3kit#464]
I just wanted to know if there are any plans on updating the TER version of this extension any time soon. We still have projects without composer on web hosts without shell access. An upload to TER would simplify upgrading for us.

**Comment by dmh** [comment]
Hi @ferdynator 

We are not able to update  theme_t3kit in TYPO3 TER because we have a dependency (Themes) which is also not published there.
Therefore, on the basis of this, we have no plans to update theme_t3kit in TER in nearest future.

Thanks.

**Comment by ferdynator** [comment]
Thank you for the answer. I'll check over there. But I do understand correctly that you would consider uploading to TER if dependencies are met?

**Comment by dmh** [comment]
Yes, if critical dependencies are met we can consider updating theme_t3kit in TER.
