### ISSUE TITLE
Customizable slider "Read more" button (SEO)

### ISSUE THREAD

**Issue by mabolek** [t3kit/theme_t3kit#49]
The slider's "Click here" button is currently hardcoded in the XLIFF file (id _contentElement.slider.linkText_).

"Read more" is a bad label for SEO. Instead, the label of the button should be customizable in the Content Element.

Currently, the "Read more" string will have to be localized for every language in order to use the slider in a new language. As far as I am aware, this is the only non-customizable frontend string in theme_t3kit.

**Comment by dmh** [comment]
#114
