### ISSUE TITLE
Can't change constants in own site_package

### ISSUE THREAD

**Issue by schneiel** [t3kit/theme_t3kit#524]
If I customize constants of theme_t3kit, they will not be adopted. That's because the **theme** is load after my site_package. When I deactivate the **theme** (add constants.txt and setup.txt of theme_t3kit to my own typoscript files in site_package), then it works, but the content elements of theme_t3kit are not load (TYPO3 throw a exception, that it looked for content elements in core folder).
How I can fix it? 

My theme_t3kit version: 2.9.0

Best regards
Elias Schneider

**Comment by edekowalski** [comment]
theme is load after my site_package = the problem 

"first theme Extension then your Sitpackage"

It works like CSS .. your Sitpackage overwrite the theme Extension.

Perhaps this helps

**Comment by schneiel** [comment]
Thank you for the fast reply. Yes I'm know, this is my problem. 

But how can I make it load first? Currently I have added my site_package to **Includes** of the backend template.
This is my first TYPO3 project and I find nothing in the documentation.

**Comment by edekowalski** [comment]
Template > and use the arrow Buttons
![Zwischenablage01](https://user-images.githubusercontent.com/2975173/57089244-48315480-6d04-11e9-807a-c66605439b12.jpg)

**Comment by schneiel** [comment]
That doesn't work for me. The Template Analyzer shows me that **theme_t3kit** is still loaded afterwards.
For this reason, the constants continue to be overwritten. Only **themes** of core will be loaded before

**Comment by edekowalski** [comment]
Also after Save the Template and reload the Page?

**Comment by schneiel** [comment]
Yes of course. I also cleared all caches.

**Comment by dmh** [comment]
Hey,
Is this issue still actual?
