### ISSUE TITLE
Incomplete dependencies check

### ISSUE THREAD

**Issue by criwe** [t3kit/theme_t3kit#95]
Hi!
When installing t3kit it doesn´t check if solr is installed. It its not, there´s no output due to a php-error.
Best,
Chris

**Comment by retosteffen** [comment]
Hi,
I had the same issue and if that could be added as a requirement that would be great.

**Comment by dmh** [comment]
https://github.com/t3kit/theme_t3kit/blob/master/composer.json#L42
